bundler_args: --without development
language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.3
  - ruby-head
notifications:
  email:
    - anthony@somersettechsolutions.co.uk
